import Image from 'next/image';
import style from './styles.module.css';

export default function SkillSection() {
    return (
        <>
            <section className={`${style.skill_section} section_inner about_section`}>
                <h2 className={'about_secTitle'}>Skills</h2>
                <ul className={style.skill_wrapper}>
                    <li>
                        <Image
                            src={'icons/React.svg'}
                            alt="React"
                            width={24}
                            height={24}
                            className={style.icon}
                        ></Image>
                        <p>React</p>
                    </li>
                    <li>
                        <Image
                            src={'icons/Next.js.svg'}
                            alt="Next.js"
                            width={24}
                            height={24}
                            className={style.icon}
                        ></Image>
                        <p>Next.js</p>
                    </li>
                    <li>
                        <Image
                            src={'icons/TypeScript.svg'}
                            alt="TypeScript"
                            width={24}
                            height={24}
                            className={style.icon}
                        ></Image>
                        <p>TypeScript</p>
                    </li>
                    <li>
                        <Image
                            src={'icons/GraphQL.svg'}
                            alt="GraphQL"
                            width={24}
                            height={24}
                            className={style.icon}
                        ></Image>
                        <p>GraphQL</p>
                    </li>
                    <li>
                        <Image
                            src={'icons/Vercel.svg'}
                            alt="Vercel"
                            width={24}
                            height={24}
                            className={style.icon}
                        ></Image>
                        <p>Vercel</p>
                    </li>
                    <li>
                        <Image
                            src={'icons/HTML5.svg'}
                            alt="HTML5"
                            width={24}
                            height={24}
                            className={style.icon}
                        ></Image>
                        <p>HTML5</p>
                    </li>
                    <li>
                        <Image
                            src={'icons/CSS3.svg'}
                            alt="CSS3"
                            width={24}
                            height={24}
                            className={style.icon}
                        ></Image>
                        <p>CSS3</p>
                    </li>
                    <li>
                        <Image
                            src={'icons/JavaScript.svg'}
                            alt="JavaScript"
                            width={24}
                            height={24}
                            className={style.icon}
                        ></Image>
                        <p>JavaScript</p>
                    </li>
                </ul>
            </section>
        </>
    );
}
